/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.example.bad;

import org.junit.jupiter.api.Test;

class CatanResourceCalculatorTest {
    @Test void testCatanResourceTrade() {
        CatanResourceCalculator.calculateAllSettlementTrades();
    }
}
